spring.application.name=restaurants

# Configuration du serveur Tomcat
server.address=0.0.0.0
server.http2.enabled=true

server.servlet.contextPath=/api

# Activation de l'encodage pour obtenir les couleurs en terminal Windows
spring.output.ansi.enabled=always

# server.port=3000
# Paramétrage de la source de données
# spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
# spring.datasource.username=postgres
# spring.datasource.password=eei425009
# spring.datasource.driver-class-name=org.postgresql.Driver

# Paramétrage de la source de données avec var env
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Paramétrage de l'ORM
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Active la génération automatique de tables par Hibernate
# DDL -> Data Definition Language
spring.jpa.hibernate.ddl-auto=update
# Choix du schéma par défaut
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.format_sql=true

# logging.level.org.springdoc=DEBUG
# logging.level.io.swagger=DEBUG

# On règle le niveau de log sur TRACE pour la sécurité (JUSTE POUR LE DEBUG)
logging.level.org.springframework.security.web=TRACE
my.name=Yanis
my.age=28

my.mails[0]=yadekalom@jehann.fr
my.mails[1]=yadekalom1@dawan.fr

my.pseudo.dofus=Jeyzen
my.pseudo.wakfu=Shekay

my.adresse.ville=Nice
my.adresse.cp=06100